language: python
python:
  - "3.8"

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils python3-pip
  - nvm install 10.15.3

script:
  # Merge single ODD files to one monolithic ODD
  - xmllint --xinclude src/mpm.odd > mpm-monolithic.odd
  
  # Get RNG file
  - curl -s -o mpm_rng.zip -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/relaxng%3Aapplication%3Axml-relaxng/conversion
  - unzip -p mpm_rng.zip document.rng >mpm.rng

  # Get DTD file
  #- curl -s -o mpm_dtd.zip -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/dtd%3Aapplication%3Axml-dtd/conversion
  #- unzip -p mpm_dtd.zip document.dtd >mpm.dtd

  # Get XSD file
  - curl -s -o mpm_xsd.zip -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/xsd%3Aapplication%3Axml-xsd/conversion
  - unzip -p mpm_xsd.zip document.xsd >mpm.xsd

  # Get docs for download assets
  - curl -s -o docs.zip -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/TEI%3Atext%3Axml/xhtml%3Aapplication%3Axhtml%2Bxml/conversion

  # Build docs for GitHub Pages
  - python3 -m pip install setuptools
  - python3 -m pip install yattag lxml
  - python3 doc_generator/transformer.py
  - cd doc_generator
  - yarn
  - yarn run generate
  - cd ..
  - mv -f doc_generator/dist docs

  # Set git tag for release
  - export VERSION=`xmllint --xpath 'string(//*[local-name()="edition"]/@n)' src/mpm.odd`
  - export DATE=`date +'%Y-%m-%d_%H-%M-%S'`
  - git tag "v${VERSION}_${DATE}"

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
    name: "MPM v$VERSION"
    file:
      - "mpm.rng"
      - "mpm.dtd"
      - "mpm.xsd"
      - "mpm-monolithic.odd"
      - "docs.zip"

  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
    keep_history: true
    target_branch: gh-pages
    local_dir: docs
