language: generic

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-utils

script:
  #- curl -s -o tei.rng https://tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng
  #- xmllint --xinclude --relaxng tei.rng src/mpm.odd > mpm-monolithic.odd
  - xmllint --xinclude src/mpm.odd > mpm-monolithic.odd
  - curl -s -o mpm.rng -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/relaxng%3Aapplication%3Axml-relaxng/conversion
  #- curl -s -o mpm.dtd -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/dtd%3Aapplication%3Axml-dtd/conversion
  - curl -s -o mpm.xsd -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/xsd%3Aapplication%3Axml-xsd/conversion
  - mkdir -p docs
  - curl -s -o docs/index.html -F upload=@mpm-monolithic.odd https://oxgarage-humanum.tei-c.org/ege-webservice/Conversions/ODD%3Atext%3Axml/ODDC%3Atext%3Axml/TEI%3Atext%3Axml/xhtml%3Aapplication%3Axhtml%2Bxml/conversion
  - sed -i -e 's/href="http:/href="https:/g' docs/index.html
  - cp docs/index.html docs.html
  - export VERSION=`xmllint --xpath 'string(//*[local-name()="edition"]/@n)' src/mpm.odd`
  - export DATE=`date +'%Y-%m-%d_%H-%M-%S'`
  - git tag "v${VERSION}_${DATE}"

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
    name: "MPM v$VERSION"
    file:
      - "mpm.rng"
      #- "mpm.dtd"
      - "mpm.xsd"
      - "mpm-monolithic.odd"
      - "docs.html"

  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
    keep_history: true
    target_branch: gh-pages
    local_dir: docs
